apiVersion: v1
kind: Secret
metadata:
  name: {{ include "udal-gateway.fullname" . }}
  labels:
    {{- include "udal-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  UDAL_BOOTSTRAP_API_KEY: {{ required "gateway.apiKey is required" .Values.gateway.apiKey | quote }}
