apiVersion: v1
kind: Service
metadata:
  name: {{ include "udal-gateway.fullname" . }}
  labels:
    {{- include "udal-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "udal-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.gateway.grpc.port }}
      targetPort: grpc
      protocol: TCP
    - name: http
      port: {{ .Values.gateway.http.port }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.gateway.metrics.port }}
      targetPort: metrics
      protocol: TCP
