# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from udal.v1 import capability_pb2 as udal_dot_v1_dot_capability__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in udal/v1/capability_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CapabilityServiceStub:
    """CapabilityService stores, versions, and serves capability schemas (F-13),
    enforced elsewhere by DeviceService during device registration (F-14) and
    property writes (F-15).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishSchema = channel.unary_unary(
                '/udal.v1.CapabilityService/PublishSchema',
                request_serializer=udal_dot_v1_dot_capability__pb2.PublishSchemaRequest.SerializeToString,
                response_deserializer=udal_dot_v1_dot_capability__pb2.PublishSchemaResponse.FromString,
                _registered_method=True)
        self.GetSchema = channel.unary_unary(
                '/udal.v1.CapabilityService/GetSchema',
                request_serializer=udal_dot_v1_dot_capability__pb2.GetSchemaRequest.SerializeToString,
                response_deserializer=udal_dot_v1_dot_capability__pb2.GetSchemaResponse.FromString,
                _registered_method=True)
        self.ListSchemas = channel.unary_unary(
                '/udal.v1.CapabilityService/ListSchemas',
                request_serializer=udal_dot_v1_dot_capability__pb2.ListSchemasRequest.SerializeToString,
                response_deserializer=udal_dot_v1_dot_capability__pb2.ListSchemasResponse.FromString,
                _registered_method=True)


class CapabilityServiceServicer:
    """CapabilityService stores, versions, and serves capability schemas (F-13),
    enforced elsewhere by DeviceService during device registration (F-14) and
    property writes (F-15).
    """

    def PublishSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSchemas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CapabilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishSchema,
                    request_deserializer=udal_dot_v1_dot_capability__pb2.PublishSchemaRequest.FromString,
                    response_serializer=udal_dot_v1_dot_capability__pb2.PublishSchemaResponse.SerializeToString,
            ),
            'GetSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchema,
                    request_deserializer=udal_dot_v1_dot_capability__pb2.GetSchemaRequest.FromString,
                    response_serializer=udal_dot_v1_dot_capability__pb2.GetSchemaResponse.SerializeToString,
            ),
            'ListSchemas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSchemas,
                    request_deserializer=udal_dot_v1_dot_capability__pb2.ListSchemasRequest.FromString,
                    response_serializer=udal_dot_v1_dot_capability__pb2.ListSchemasResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'udal.v1.CapabilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('udal.v1.CapabilityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CapabilityService:
    """CapabilityService stores, versions, and serves capability schemas (F-13),
    enforced elsewhere by DeviceService during device registration (F-14) and
    property writes (F-15).
    """

    @staticmethod
    def PublishSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/udal.v1.CapabilityService/PublishSchema',
            udal_dot_v1_dot_capability__pb2.PublishSchemaRequest.SerializeToString,
            udal_dot_v1_dot_capability__pb2.PublishSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/udal.v1.CapabilityService/GetSchema',
            udal_dot_v1_dot_capability__pb2.GetSchemaRequest.SerializeToString,
            udal_dot_v1_dot_capability__pb2.GetSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSchemas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/udal.v1.CapabilityService/ListSchemas',
            udal_dot_v1_dot_capability__pb2.ListSchemasRequest.SerializeToString,
            udal_dot_v1_dot_capability__pb2.ListSchemasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
