# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: udal/v1/capability.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'udal/v1/capability.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18udal/v1/capability.proto\x12\x07udal.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x01\n\x10\x43\x61pabilitySchema\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0b\n\x03raw\x18\x04 \x01(\x0c\x12\x30\n\x0cpublished_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"&\n\x14PublishSchemaRequest\x12\x0e\n\x06schema\x18\x01 \x01(\x0c\"B\n\x15PublishSchemaResponse\x12)\n\x06schema\x18\x01 \x01(\x0b\x32\x19.udal.v1.CapabilitySchema\"1\n\x10GetSchemaRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\">\n\x11GetSchemaResponse\x12)\n\x06schema\x18\x01 \x01(\x0b\x32\x19.udal.v1.CapabilitySchema\"\"\n\x12ListSchemasRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"A\n\x13ListSchemasResponse\x12*\n\x07schemas\x18\x01 \x03(\x0b\x32\x19.udal.v1.CapabilitySchema2\xc4\x02\n\x11\x43\x61pabilityService\x12\x66\n\rPublishSchema\x12\x1d.udal.v1.PublishSchemaRequest\x1a\x1e.udal.v1.PublishSchemaResponse\"\x16\x82\xd3\xe4\x93\x02\x10\"\x0b/v1/schemas:\x01*\x12h\n\tGetSchema\x12\x19.udal.v1.GetSchemaRequest\x1a\x1a.udal.v1.GetSchemaResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/schemas/{name}/{version}\x12]\n\x0bListSchemas\x12\x1b.udal.v1.ListSchemasRequest\x1a\x1c.udal.v1.ListSchemasResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\x0b/v1/schemasB;Z9github.com/paulefl/udal/code/api/proto/gen/udal/v1;udalv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'udal.v1.capability_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/paulefl/udal/code/api/proto/gen/udal/v1;udalv1'
  _globals['_CAPABILITYSERVICE'].methods_by_name['PublishSchema']._loaded_options = None
  _globals['_CAPABILITYSERVICE'].methods_by_name['PublishSchema']._serialized_options = b'\202\323\344\223\002\020\"\013/v1/schemas:\001*'
  _globals['_CAPABILITYSERVICE'].methods_by_name['GetSchema']._loaded_options = None
  _globals['_CAPABILITYSERVICE'].methods_by_name['GetSchema']._serialized_options = b'\202\323\344\223\002\036\022\034/v1/schemas/{name}/{version}'
  _globals['_CAPABILITYSERVICE'].methods_by_name['ListSchemas']._loaded_options = None
  _globals['_CAPABILITYSERVICE'].methods_by_name['ListSchemas']._serialized_options = b'\202\323\344\223\002\r\022\013/v1/schemas'
  _globals['_CAPABILITYSCHEMA']._serialized_start=101
  _globals['_CAPABILITYSCHEMA']._serialized_end=234
  _globals['_PUBLISHSCHEMAREQUEST']._serialized_start=236
  _globals['_PUBLISHSCHEMAREQUEST']._serialized_end=274
  _globals['_PUBLISHSCHEMARESPONSE']._serialized_start=276
  _globals['_PUBLISHSCHEMARESPONSE']._serialized_end=342
  _globals['_GETSCHEMAREQUEST']._serialized_start=344
  _globals['_GETSCHEMAREQUEST']._serialized_end=393
  _globals['_GETSCHEMARESPONSE']._serialized_start=395
  _globals['_GETSCHEMARESPONSE']._serialized_end=457
  _globals['_LISTSCHEMASREQUEST']._serialized_start=459
  _globals['_LISTSCHEMASREQUEST']._serialized_end=493
  _globals['_LISTSCHEMASRESPONSE']._serialized_start=495
  _globals['_LISTSCHEMASRESPONSE']._serialized_end=560
  _globals['_CAPABILITYSERVICE']._serialized_start=563
  _globals['_CAPABILITYSERVICE']._serialized_end=887
# @@protoc_insertion_point(module_scope)
