# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from udal.v1 import device_pb2 as udal_dot_v1_dot_device__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in udal/v1/device_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceServiceStub:
    """─── DeviceService ────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDevice = channel.unary_unary(
                '/udal.v1.DeviceService/GetDevice',
                request_serializer=udal_dot_v1_dot_device__pb2.GetDeviceRequest.SerializeToString,
                response_deserializer=udal_dot_v1_dot_device__pb2.GetDeviceResponse.FromString,
                _registered_method=True)
        self.ListDevices = channel.unary_unary(
                '/udal.v1.DeviceService/ListDevices',
                request_serializer=udal_dot_v1_dot_device__pb2.ListDevicesRequest.SerializeToString,
                response_deserializer=udal_dot_v1_dot_device__pb2.ListDevicesResponse.FromString,
                _registered_method=True)
        self.RegisterDevice = channel.unary_unary(
                '/udal.v1.DeviceService/RegisterDevice',
                request_serializer=udal_dot_v1_dot_device__pb2.RegisterDeviceRequest.SerializeToString,
                response_deserializer=udal_dot_v1_dot_device__pb2.RegisterDeviceResponse.FromString,
                _registered_method=True)
        self.DeleteDevice = channel.unary_unary(
                '/udal.v1.DeviceService/DeleteDevice',
                request_serializer=udal_dot_v1_dot_device__pb2.DeleteDeviceRequest.SerializeToString,
                response_deserializer=udal_dot_v1_dot_device__pb2.DeleteDeviceResponse.FromString,
                _registered_method=True)
        self.GetProperty = channel.unary_unary(
                '/udal.v1.DeviceService/GetProperty',
                request_serializer=udal_dot_v1_dot_device__pb2.GetPropertyRequest.SerializeToString,
                response_deserializer=udal_dot_v1_dot_device__pb2.GetPropertyResponse.FromString,
                _registered_method=True)
        self.SetProperty = channel.unary_unary(
                '/udal.v1.DeviceService/SetProperty',
                request_serializer=udal_dot_v1_dot_device__pb2.SetPropertyRequest.SerializeToString,
                response_deserializer=udal_dot_v1_dot_device__pb2.SetPropertyResponse.FromString,
                _registered_method=True)
        self.SendCommand = channel.unary_unary(
                '/udal.v1.DeviceService/SendCommand',
                request_serializer=udal_dot_v1_dot_device__pb2.SendCommandRequest.SerializeToString,
                response_deserializer=udal_dot_v1_dot_device__pb2.SendCommandResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/udal.v1.DeviceService/Subscribe',
                request_serializer=udal_dot_v1_dot_device__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=udal_dot_v1_dot_device__pb2.SubscribeResponse.FromString,
                _registered_method=True)
        self.StreamCommands = channel.stream_stream(
                '/udal.v1.DeviceService/StreamCommands',
                request_serializer=udal_dot_v1_dot_device__pb2.CommandResult.SerializeToString,
                response_deserializer=udal_dot_v1_dot_device__pb2.Command.FromString,
                _registered_method=True)


class DeviceServiceServicer:
    """─── DeviceService ────────────────────────────────────────────────────────────

    """

    def GetDevice(self, request, context):
        """Device registry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProperty(self, request, context):
        """Property access
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCommand(self, request, context):
        """Command execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Streaming
        WebSocket / SSE via grpc-gateway streaming — no HTTP annotation (streaming not supported by grpc-gateway v2 REST mapping)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCommands(self, request_iterator, context):
        """StreamCommands is opened by a device-side SDK (after RegisterDevice) that
        is connected directly over gRPC rather than through a transport adapter.
        The target device_id is supplied via the "x-device-id" metadata header
        when the stream is opened, not as a per-message field, since this is a
        bidirectional stream: the server pushes Command as SendCommand calls come
        in for that device, and the device sends back one CommandResult per
        Command it received. SendCommand routes to this channel when a device is
        connected this way, falling back to the (not yet implemented) transport
        adapter path otherwise.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDevice,
                    request_deserializer=udal_dot_v1_dot_device__pb2.GetDeviceRequest.FromString,
                    response_serializer=udal_dot_v1_dot_device__pb2.GetDeviceResponse.SerializeToString,
            ),
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=udal_dot_v1_dot_device__pb2.ListDevicesRequest.FromString,
                    response_serializer=udal_dot_v1_dot_device__pb2.ListDevicesResponse.SerializeToString,
            ),
            'RegisterDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDevice,
                    request_deserializer=udal_dot_v1_dot_device__pb2.RegisterDeviceRequest.FromString,
                    response_serializer=udal_dot_v1_dot_device__pb2.RegisterDeviceResponse.SerializeToString,
            ),
            'DeleteDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDevice,
                    request_deserializer=udal_dot_v1_dot_device__pb2.DeleteDeviceRequest.FromString,
                    response_serializer=udal_dot_v1_dot_device__pb2.DeleteDeviceResponse.SerializeToString,
            ),
            'GetProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProperty,
                    request_deserializer=udal_dot_v1_dot_device__pb2.GetPropertyRequest.FromString,
                    response_serializer=udal_dot_v1_dot_device__pb2.GetPropertyResponse.SerializeToString,
            ),
            'SetProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProperty,
                    request_deserializer=udal_dot_v1_dot_device__pb2.SetPropertyRequest.FromString,
                    response_serializer=udal_dot_v1_dot_device__pb2.SetPropertyResponse.SerializeToString,
            ),
            'SendCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommand,
                    request_deserializer=udal_dot_v1_dot_device__pb2.SendCommandRequest.FromString,
                    response_serializer=udal_dot_v1_dot_device__pb2.SendCommandResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=udal_dot_v1_dot_device__pb2.SubscribeRequest.FromString,
                    response_serializer=udal_dot_v1_dot_device__pb2.SubscribeResponse.SerializeToString,
            ),
            'StreamCommands': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamCommands,
                    request_deserializer=udal_dot_v1_dot_device__pb2.CommandResult.FromString,
                    response_serializer=udal_dot_v1_dot_device__pb2.Command.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'udal.v1.DeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('udal.v1.DeviceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceService:
    """─── DeviceService ────────────────────────────────────────────────────────────

    """

    @staticmethod
    def GetDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/udal.v1.DeviceService/GetDevice',
            udal_dot_v1_dot_device__pb2.GetDeviceRequest.SerializeToString,
            udal_dot_v1_dot_device__pb2.GetDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/udal.v1.DeviceService/ListDevices',
            udal_dot_v1_dot_device__pb2.ListDevicesRequest.SerializeToString,
            udal_dot_v1_dot_device__pb2.ListDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/udal.v1.DeviceService/RegisterDevice',
            udal_dot_v1_dot_device__pb2.RegisterDeviceRequest.SerializeToString,
            udal_dot_v1_dot_device__pb2.RegisterDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/udal.v1.DeviceService/DeleteDevice',
            udal_dot_v1_dot_device__pb2.DeleteDeviceRequest.SerializeToString,
            udal_dot_v1_dot_device__pb2.DeleteDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/udal.v1.DeviceService/GetProperty',
            udal_dot_v1_dot_device__pb2.GetPropertyRequest.SerializeToString,
            udal_dot_v1_dot_device__pb2.GetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/udal.v1.DeviceService/SetProperty',
            udal_dot_v1_dot_device__pb2.SetPropertyRequest.SerializeToString,
            udal_dot_v1_dot_device__pb2.SetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/udal.v1.DeviceService/SendCommand',
            udal_dot_v1_dot_device__pb2.SendCommandRequest.SerializeToString,
            udal_dot_v1_dot_device__pb2.SendCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/udal.v1.DeviceService/Subscribe',
            udal_dot_v1_dot_device__pb2.SubscribeRequest.SerializeToString,
            udal_dot_v1_dot_device__pb2.SubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCommands(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/udal.v1.DeviceService/StreamCommands',
            udal_dot_v1_dot_device__pb2.CommandResult.SerializeToString,
            udal_dot_v1_dot_device__pb2.Command.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
